services:
  esic-camarafranciscomorato:
    container_name: container_name
    build: path
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:8080
    env_file:
      - ./environments/.env
    volumes:
      - ./volumes:/data

volumes:
  data:
    
